#tomcat port
server:
  port: 9001
#jsp
spring:
  #mvc:
    #view:
      #prefix: /WEB-INF/ipgo/
      #suffix: .jsp
  devtools:
    livereload:
      enabled: true
#mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/woo?serverTimezone=Asia/Seoul
    username: woo
    password: 1234
#mybatis
mybatis:
  type-aliases-package: boot.data.dto,boot.data.mapper
  mapper-locations:
  - /mapper/**/*.xml
